spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.30.50.21:3306/sampledb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
    username: root
    password: IO6CaRKPgqYPKoVr   
